services:
  - type: web
    name: sms-spam-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: sh setup.sh && streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHON_VERSION
        value: 3.11.0



